### ISSUE TITLE
Error when executing run.sh 

### ISSUE THREAD

**Issue by wureka** [GRIDAPPSD/gridappsd-docker#54]
Environment:
- Ubuntu 20.04 LTS 64bit
- Docker 23.0
- Docker compose 1.25.0
- Python 3.8.10

Below is the re-produced steps:

```
alexji@zorinos:~/tmp/gridappsd-docker$ ./run.sh 
Compose files: -f docker-compose.yml 
 
Getting blazegraph status
 
Pulling updated containers
Pulling blazegraph ... done
Pulling redis      ... done
Pulling mysql      ... done
Pulling gridappsd  ... done
Pulling viz        ... done
Pulling sample_app ... done
Pulling proven     ... done
Pulling influxdb   ... done
 
Starting the docker containers
 
 
Creating network "gridappsd-docker_default" with the default driver
Creating influxdb   ... done
Creating mysql      ... done
Creating proven     ... done
Creating redis      ... done
Creating blazegraph ... done
Creating gridappsd  ... 

ERROR: for gridappsd  a bytes-like object is required, not 'str'

ERROR: for gridappsd  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/9c33a5c584941625fe3bd2b4c806293785ac4fae0e887029f7fdb51f65b388ce/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/compose/service.py", line 625, in start_container
    container.start()
  File "/usr/lib/python3/dist-packages/compose/container.py", line 241, in start
    return self.client.start(self.id, **options)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint gridappsd (f880bef12c94b631e16ad1965674c17aabc2ddfd67cb362802ddf033d3282aaa): Bind for 0.0.0.0:8000 failed: port is already allocated'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1088, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 565, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 548, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 545, in execute_convergence_plan
    return self._execute_convergence_create(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 460, in _execute_convergence_create
    containers, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 465, in <lambda>
    lambda service_name: create_and_start(self, service_name.number),
  File "/usr/lib/python3/dist-packages/compose/service.py", line 457, in create_and_start
    self.start_container(container)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 627, in start_container
    if "driver failed programming external connectivity" in ex.explanation:
TypeError: a bytes-like object is required, not 'str'
 
Error starting containers
Exiting 
 
alexji@zorinos:~/tmp/gridappsd-docker$ 

```
Any suggestion ?

**Comment by wureka** [comment]
My bad, the port 8000 is occupied

**Comment by poorva1209** [comment]
Closing this issue as it was a pre-occupied port issue.
